name: hello world workflow

on:
  push:
    branches:
        -main
  pull_request:
    branches:
        -main
  workflow_dispatch:
jobs:
  first_job:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: hello world
        run: echo "Hello World"
        shell: bash
        
  goodbye:
    runs_on: ubuntu-latest
    steps:
      - name: hello world
        run: echo "Hello World"
        shell: bash
    
